spring:
  application:
    name: catalog-service

server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s

polar:
  greeting: Welcome to the local book catalog from cfg file!